In [ ]:
#Week 1 Workshop

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

1. Initialize an empty array with size 2X2.

In [3]:
import numpy as np
two_by_two_array = np.empty((2, 2))
two_by_two_array

array([[4.11811320e-315, 0.00000000e+000],
       [6.62277022e-310, 5.29940345e-317]])

2. Initialize an all one array with size 4X2.

In [4]:


four_by_four_array = np.empty((4, 4))
four_by_four_array

array([[4.14330794e-315, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [8]:

rows = 2
columns = 3
custom_array = np.full((rows,columns), fill_value = 2)
custom_array

array([[2, 2, 2],
       [2, 2, 2]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [7]:

given_array = np.array([[1, 2, 3], [4, 5, 6]])
new_array = np.zeros_like(given_array)
print(new_array)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [6]:

given_array = np.array([[1, 2, 3], [4, 5, 6]])
new_array = np.ones_like(given_array)
print(new_array)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [5]:

new_list = [1, 2, 3, 4]
new_list= np.array(new_list)
print(type(new_list))

<class 'numpy.ndarray'>


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [ ]:
import numpy as np

array1 = np.arange(10,50)
array1

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}


In [15]:
import numpy as np

array2 = np.arange(0,9)
array2 = np.reshape(array2, (3,3))
array2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}


In [14]:
import numpy as np

array3 = np.eye(3)
array3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}


In [13]:
import numpy as np

array4 = np.random.random(30) * 5
array4_mean = array4.mean()
float(array4_mean)

2.0632472058963507


5. Create a 10X10 array with random values and find the minimum and maximum values.


In [12]:
import numpy as np

array5 = np.random.randint(0, 100, size = (10, 10))
min = np.min(array5)
max = np.max(array5)
print(f"Array : {array5}\n Min : {min} \n Max : {max}")

Array : [[31 85 29 72 49 21 87 85 58 28]
 [80 74 48 88 76 69 40 83 50 96]
 [95 27 62 30 52  4  1  1  0 91]
 [41 97 13 21 55 52 39 48 50 84]
 [27 86 18 31 23 14 21 98 56 78]
 [15 84 63 70 83 62 49 99 13 22]
 [88 94 68  6 51 14 48 88  9 34]
 [59 58 17 28 27 82 97 64 49 90]
 [44 21  3 30 75 76 62  3 99 52]
 [71  3 27 92  5  3 83 49 90 45]]
 Min : 0 
 Max : 99


6. Create a zero array of size 10 and replace 5th element with 1.


In [11]:
import numpy as np

array6 = np.zeros(10)
print("Initial Array : ", array6)
array6[4] = 1
print("After alteration : ", array6)

Initial Array :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After alteration :  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [10]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = np.flip(arr)
print(f"Array : {arr}")
print(f"Reversed Array : {reversed_array}")

Array : [1 2 0 0 4 0]
Reversed Array : [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.


In [9]:
import numpy as np

two_dims_array = np.zeros((2, 2))
two_dims_array[0][0] = 1
two_dims_array[1][1] = 1
print(two_dims_array)

[[1. 0.]
 [0. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [8]:
import numpy as np

checkerboard_array = np.zeros((8,8))

for i in range(8):
  for j in range(8):
    if (i % 2 == 0 and j % 2 != 0):
      checkerboard_array[i][j] = 1
    elif(i % 2 != 0 and j % 2 == 0):
      checkerboard_array[i][j] = 1
checkerboard_array

#alternative : np.arange(10, 50)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem - 3: Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

1 - Add the two array

In [9]:


x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6],[7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

np.add(x, y)


array([[ 6,  8],
       [10, 13]])

2 - Subtract the two array

In [10]:

np.subtract(x, y)


array([[-4, -4],
       [-4, -3]])

3 - Multiply the array with any integers of your choice.

In [11]:

np.multiply(x, 4)


array([[ 4,  8],
       [12, 20]])

4 - Find the square of each element of the array.

In [12]:

np.power(x, 2)


array([[ 1,  4],
       [ 9, 25]])

5 - Find the dot product between : v(and)w ; x(and)v; x(and)y

In [13]:

print("Dot product between v and w : " , np.dot(v, w))
print("Dot product between x and v : " , np.dot(x, v))
print("Dot product between x and y : " , np.dot(x, y))


Dot product between v and w :  219
Dot product between x and v :  [29 77]
Dot product between x and y :  [[19 22]
 [50 58]]


6 - Concatenate x(and)y along row and concatenate v(and)w along column. {Hint : try np.concatenate() or np.vstack() functions}.

In [14]:

np.hstack((x, y))
np.vstack((v, w))


array([[ 9, 10],
       [11, 12]])

7 - Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [15]:

np.concatenate((x, v))


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Arrays x and v cannot be concatenated because all the input arrays must have same number of dimensions, but array x has 2 dimensions and array v has 1 dimension. Hence, causing dimension mismatch.

Problem 4 - Matrix Operations

For the following arrays:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [17]:

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#Prove the following with NumPy:

#1 - Prove : A.A^(-1) = I

IoA = np.linalg.inv(A)

print(np.dot(A, IoA))
print("Since the dot Product of A and its inverse is an identity matrix. Hence, A.A^(-1) = I")



[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Since the dot Product of A and its inverse is an identity matrix. Hence, A.A^(-1) = I


2 - Prove A.B != B.A


In [17]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("A.B : ", np.dot(A, B))
print("B.A : ", np.dot(B, A))
print("Since A.B is not equal to B.A . Therefore, A.B != B.A")

A.B :  [[23 13]
 [51 29]]
B.A :  [[36 44]
 [13 16]]
Since A.B is not equal to B.A . Therefore, A.B != B.A


3 - Prove (A.B)^T = B^T.A^T

In [19]:

abdot = np.dot(A,B)
abdot_transpose = np.transpose(abdot)

atranspose = np.transpose(A)
btranspose = np.transpose(B)

btat = np.dot(btranspose, atranspose)

print("(A.B)^T : ", abdot_transpose)
print("B^T.A^T : ", btat)
print("Since, the values of result match. Hence, A.B)^T = B^T.A^T .")


(A.B)^T :  [[23 51]
 [13 29]]
B^T.A^T :  [[23 51]
 [13 29]]
Since, the values of result match. Hence, A.B)^T = B^T.A^T .


Solve the following system of linear equation using inverse methods

2x - 3y + z = -1

x - y + 2z = -3

3x + y - z = 9

{Hint : First use Numpy array to represent the equation in Matrix form. Then Solve for A.X = B}

Now : solve the above equation using np.linalg.inv function. [Explore more about 'linalg' function of Numpy]

In [21]:

X = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
Y = np.array([-1, -3, 9])

#X.Z =Y
IoX = np.linalg.inv(X)
Z = np.dot(IoX, Y)
print("Answer : ", Z)
print("Hence, x = ", Z[0], ", y = ", Z[1], ", and z = ", Z[2])



Answer :  [ 2.  1. -2.]
Hence, x =  2.0 , y =  1.0 , and z =  -2.0


4.2 : Experimenting : How Fast is Numpy?

1. Element-wise Addition:

  • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

  • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [21]:
import numpy as np
from timeit import timeit

python_list = []

for i in range(1000001):
  python_list.append(i)

def add_python(python_list):
  sum_of_python_list = 0
  for i in range(1000001):
    sum_of_python_list += python_list[i]
  return sum_of_python_list

numpy_list = np.arange(1000000)

def add_numpy(numpy_list):
  sum_of_numpy_array = numpy_list.sum()
  return sum_of_numpy_array

python_time = timeit("add_python(python_list)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(numpy_list)", globals=globals(), number=100)

print(f"Pure Python addition : {python_time:.6f} seconds per loop")
print(f"Numpy addition : {numpy_time:.6f} seconds per loop")



Pure Python addition : 6.519838 seconds per loop
Numpy addition : 0.035671 seconds per loop


2. Element-wise Multiplication:

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [26]:
import numpy as np
from timeit import timeit

python_list1 = []
python_list2 = []

for i in range(1000001):
  python_list1.append(i)
for j in range(1000001, 0, -1):
  python_list2.append(j)

def multiplication_python(python_list1, python_list2):
  new_python_list = []
  for i in range(1000000):
    new_python_list.append(python_list1[i] * python_list2[i])
  return new_python_list

numpy_list1 = np.arange(1000000)
numpy_list2 = np.arange(1000000)

def multiplication_numpy(numpy_list1, numpy_list2):
  return numpy_list1 * numpy_list2

python_time = timeit("multiplication_python(python_list1, python_list2)", globals=globals(), number=100)
numpy_time = timeit("multiplication_numpy(numpy_list1, numpy_list2)", globals=globals(), number=100)

print(f"Pure Python addition : {python_time:.6f} seconds per loop")
print(f"Numpy addition : {numpy_time:.6f} seconds per loop")

Pure Python addition : 10.193119 seconds per loop
Numpy addition : 0.178865 seconds per loop


3. Dot Product:

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [28]:
import numpy as np
from timeit import timeit

python_list1 = []
python_list2 = []

for i in range(1000001):
  python_list1.append(i)
for j in range(1000001, 0, -1):
  python_list2.append(j)

def dot_python(python_list1, python_list2):
  total = 0
  for i in range(1000000):
    total += python_list1[i] * python_list2[i]
  return total

numpy_list1 = np.arange(1000000)
numpy_list2 = np.arange(1000000)

def dot_numpy(numpy_list1, numpy_list2):
  return np.dot(numpy_list1, numpy_list2)

python_time = timeit("dot_python(python_list1, python_list2)", globals=globals(), number=100)
numpy_time = timeit("dot_numpy(numpy_list1, numpy_list2)", globals=globals(), number=100)

print(f"Pure Python addition : {python_time:.6f} seconds per loop")
print(f"Numpy addition : {numpy_time:.6f} seconds per loop")

Pure Python addition : 10.451423 seconds per loop
Numpy addition : 0.107705 seconds per loop


4. Matrix Multiplication:

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [22]:
import numpy as np
import random
from timeit import timeit

python_matrix1 = []
python_matrix2 = []

for i in range(100):
  row = []
  for j in range(100):
    row.append(random.random())
  python_matrix1.append(row)

for i in range(100):
  row = []
  for j in range(100):
    row.append(random.random())
  python_matrix2.append(row)


def matrix_python(python_matrix1, python_matrix2):
  result = []
  for i in range(100):
    row = []
    for j in range(100):
      res = 0
      for k in range(100):
        res += python_matrix1[i][k] + python_matrix2[i][k]
        row.append(res)
    result.append(row)
  return result

numpy_matrix1 = np.random.rand(100)
numpy_matrix2 = np.random.rand(100)

def matrix_numpy(numpy_matrix1, numpy_matrix2):
  return np.dot(numpy_matrix1, numpy_matrix2)

python_time = timeit("matrix_python(python_matrix1, python_matrix2)", globals=globals(), number=100)
numpy_time = timeit("matrix_numpy(numpy_matrix1, numpy_matrix2)", globals=globals(), number=100)

print(f"Pure Python addition : {python_time:.6f} seconds per loop")
print(f"Numpy addition : {numpy_time:.6f} seconds per loop")

Pure Python addition : 12.199133 seconds per loop
Numpy addition : 0.000300 seconds per loop
