In [ ]:
#Week 1 Workshop
import numpy as np

In [ ]:
#4.1
# Problem 1 - Array Creation

#1 - Initialize an empty array with size 2X2

two_by_two_array = np.empty((2, 2))

#2 - Initialize an all one array with size 4X2

four_by_four_array = np.empty((4, 4))

#3 - Return a new array of given shape and type, filled with fill value {Hink : np.full}

rows = 2
columns = 3
custom_array = np.full((rows,columns), fill_value = 2)
print(custom_array)

#4 - Return a new array of zero with same shape and type as a given array.{Hint : np.zeros_like}

given_array = np.array([[1, 2, 3], [4, 5, 6]])
new_array = np.zeros_like(given_array)
print(new_array)

#5 - Return a new array of ones with same shape and type as a given array. {Hint : np.ones_like}

given_array = np.array([[1, 2, 3], [4, 5, 6]])
new_array = np.ones_like(given_array)
print(new_array)

#6 - For an existing list new_list = [1, 2, 3, 4] convert to an numpy array. {Hint : np.array()}

new_list = [1, 2, 3, 4]
new_list= np.array(new_list)
print(type(new_list))

[[2 2 2]
 [2 2 2]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>


In [7]:
from re import M
import numpy as np
#Problem 2 - Array Manipulation : Numerical Ranges and Array Indexing
#1 - Create an array with values ranging from 10 to 49. {Hint : np.arrange()}

array1 = np.arange(10,50)
array1

#2 - Create a 3x3 matrix with values ranging from 0 to 8. {Hint : look for np.reshape()}

array2 = np.arange(0,9)
array2 = np.reshape(array2, (3,3))
array2

#3 - Create a 3x3 identity matrix. {Hint : np.eye()}

array3 = np.eye(3)
array3

#4 - Create a random array of size 30 and find the mean of the array. {Hint : check for np.random.random() and array.mean() function}

array4 = np.random.random(30) * 5
array4_mean = array4.mean()
float(array4_mean)

#5 - Create a 10x10 array with random values and find the minimum and maximum values.

array5 = np.random.randint(0, 100, size = (10, 10))
min = np.min(array5)
max = np.max(array5)
print(f"Array : {array5}\n Min : {min} \n Max : {max}")

#6 - Create a zero array of size 10 and replace 5th element with 1.

array6 = np.zeros(10)
print("Initial Array : ", array6)
array6[4] = 1
print("After alteration : ", array6)

#7 = Reverse an array arr = [1, 2, 0, 0, 4, 0].

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = np.flip(arr)
print(f"Array : {arr}")
print(f"Reversed Array : {reversed_array}")

#8 - Create a 2d array with 1 on border and 0 inside.

two_dims_array = np.zeros((2, 2))
two_dims_array[0][0] = 1
two_dims_array[1][1] = 1
print(two_dims_array)

#9 - Create a 8x8 matrix and fill it with a checkerboard pattern.

checkerboard_array = np.zeros((8,8))

for i in range(8):
  for j in range(8):
    if (i % 2 == 0 and j % 2 != 0):
      checkerboard_array[i][j] = 1
    elif(i % 2 != 0 and j % 2 == 0):
      checkerboard_array[i][j] = 1
checkerboard_array



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [25]:
#Problem 3 - Array Operations

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6],[7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#1 - Add the two array

np.add(x, y)

#2 - Subtract the two array

np.subtract(x, y)

#3 - Multiply the array with any integers of your choice.

np.multiply(x, 4)

#4 - Find the square of each element of the array.

np.power(x, 2)

#5 - Find the dot product between : v(and)w ; x(and)v; x(and)y

# print("Dot product between v and w : " , np.dot(v, w))
# print("Dot product between x and v : " , np.dot(x, v))
# print("Dot product between x and y : " , np.dot(x, y))

#6 - Concatenate x(and)y along row and concatenate v(and)w along column. {Hint : try np.concatenate() or np.vstack() functions}.

# np.hstack((x, y))
# np.vstack((v, w))

#7 - Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

np.concatenate((x, v))

#Arrays x and v cannot be concatenated because all the input arrays must have same number of dimensions, but array x has 2 dimensions and array v has 1 dimension. Hence, causing dimension mismatch.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [30]:
#Problem 4 - Matrix Operations

#For the following arrays:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#Prove the following with NumPy:

#1 - Prove : A.A^(-1) = 1

IoA = np.linalg.inv(A)

np.dot(A, IoA)

#2 - Prove A.B != B.A

print("A.B : ", np.dot(A, B))
print("B.A : ", np.dot(B, A))

#3 - Prove (A.B)^T = B^T.A^T

abdot = np.dot(A,B)
abdot_transpose = np.transpose(abdot)

atranspose = np.transpose(A)
btranspose = np.transpose(B)

btat = np.dot(btranspose, atranspose)

print("(A.B)^T : ", abdot_transpose)
print("B^T.A^T : ", btat)



#Solve the following system of linear equation using inverse methods

#2x - 3y + z = -1
#x - y + 2z = -3
#3x + y - z = 9

X = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
Y = np.array([-1, -3, 9])

#X.Z =Y
IoX = np.linalg.inv(X)
Z = np.dot(IoX, Y)
print(Z)

#{Hint : First use Numpy array to represent the equation in Matrix form. Then Solve for A.X = B}



#Now : solve the above equation using np.linalg.inv function. [Explore more about 'linalg' function of Numpy]



A.B :  [[23 13]
 [51 29]]
B.A :  [[36 44]
 [13 16]]
(A.B)^T :  [[23 51]
 [13 29]]
B^T.A^T :  [[23 51]
 [13 29]]
[ 2.  1. -2.]
